// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseSavePath(arg1) {
  return window['go']['main']['App']['ChooseSavePath'](arg1);
}

export function GetDefaultOllamaSettings() {
  return window['go']['main']['App']['GetDefaultOllamaSettings']();
}

export function ImproveText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImproveText'](arg1, arg2, arg3, arg4);
}

export function OpenDocument() {
  return window['go']['main']['App']['OpenDocument']();
}

export function WriteDocument(arg1, arg2) {
  return window['go']['main']['App']['WriteDocument'](arg1, arg2);
}
