// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseSavePath(arg1:string):Promise<string>;

export function GetDefaultSettings():Promise<main.DefaultSettings>;

export function ImproveText(arg1:string,arg2:string,arg3:main.AIConfig):Promise<string>;

export function OpenDocument():Promise<main.Document>;

export function WriteDocument(arg1:string,arg2:Array<number>):Promise<void>;
